import { Inter } from "next/font/google";
import "./globals.css";
import AuthContextProvider from "@/app/store/auth-context";
import BooksContextProvider from "@/app/store/books-context";
import Header from "./components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <BooksContextProvider>
            <Header />
            {children}
          </BooksContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
